create table tb_author (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_book (uuid uuid not null, title varchar(255) not null unique, primary key (uuid));
create table tb_publisher (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_review (uuid uuid not null, comment varchar(255) not null, primary key (uuid));
create table tb_author (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_book (uuid uuid not null, title varchar(255) not null unique, primary key (uuid));
create table tb_publisher (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_review (uuid uuid not null, comment varchar(255) not null, primary key (uuid));
create table tb_author (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_book (uuid uuid not null, title varchar(255) not null unique, primary key (uuid));
create table tb_publisher (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_review (uuid uuid not null, comment varchar(255) not null, primary key (uuid));
create table tb_author (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_book (uuid uuid not null, title varchar(255) not null unique, primary key (uuid));
create table tb_publisher (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_review (uuid uuid not null, comment varchar(255) not null, primary key (uuid));
create table tb_author (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_book (uuid uuid not null, title varchar(255) not null unique, primary key (uuid));
create table tb_publisher (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_review (uuid uuid not null, comment varchar(255) not null, primary key (uuid));
create table tb_author (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_book (uuid uuid not null, title varchar(255) not null unique, primary key (uuid));
create table tb_publisher (uuid uuid not null, name varchar(255) not null unique, primary key (uuid));
create table tb_review (uuid uuid not null, comment varchar(255) not null, primary key (uuid));
